dist: trusty
sudo: required
language: java

addons:
  sonarcloud:
    organization: "$jianglinyao1996"
    token:
      secure: "$972c3632ee6909bed79ba1288194166a27093656"

jdk:
  - oraclejdk8

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
   - mvn install -Dmaven.test.skip=true
   - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
  
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
