addons:
  sonarcloud:
    organization: "jianglinyao1996"
    token:
      secure: "63cf5bae59ca96f19fda4404cc7608e00a3eb9dd" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
